### ISSUE TITLE
ng add @ngx-pwa/local-storage throws exception

### ISSUE THREAD

**Issue by slo-cap3** [cyrilletuzi/angular-async-local-storage#242]
![grafik](https://user-images.githubusercontent.com/50576969/68112557-e55a8900-fef1-11e9-8c82-56778c80c8ae.png)

**error log:**

[error] Error: Cannot find module '@schematics/angular/utility/workspace'
Require stack:
- C:\projects\sm3_app\node_modules\@ngx-pwa\local-storage\schematics\utility\config.js
- C:\projects\sm3_app\node_modules\@ngx-pwa\local-storage\schematics\ng-add\index.js
- C:\projects\sm3_app\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\projects\sm3_app\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\projects\sm3_app\node_modules\@angular\cli\utilities\json-schema.js
- C:\projects\sm3_app\node_modules\@angular\cli\models\command-runner.js
- C:\projects\sm3_app\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\sebas\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\sebas\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\projects\sm3_app\node_modules\@ngx-pwa\local-storage\schematics\utility\config.js:13:21)      at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\projects\sm3_app\node_modules\@ngx-pwa\local-storage\schematics\ng-add\index.js:13:18)        at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)

**Comment by cyrilletuzi** [comment]
Thanks for your report. Indeed the `ng add @ngx-pwa/local-storage` requires `@schematics/angular` to work. It's included when working with the official Angular CLI. I'll add instructions for non-CLI users.

**Comment by cyrilletuzi** [comment]
@slo-cap3 I answered you quickly from work, but when thinking of it again, if you're able to do `ng add` at all means you're in a project managed with Angular CLI, right? If that's the case, it's not normal `@schematics/angular` is not available, I'd need you to share your Angular config (`ng version` in your project path).

**Comment by slo-cap3** [comment]
ah ok, i actually was wondering what you meant by non-CLI ;) I scaffolded this project using ionic, so i thought it is because of that? I know that ionic is doing al lot of custom stuff.

This is the output of `ng version`
![grafik](https://user-images.githubusercontent.com/50576969/68189128-07fca880-ffab-11e9-995d-18709828fa09.png)

**Comment by slo-cap3** [comment]
i can see that `@schematics/angular` is on v7 and @angular/cli on v8. Could this be the problem? I just upgraded the angular version from 7 to 8 (so that i can use the current version of your lib ;) ), but migration did not run through to the end because of problems with the AOT compiler.

**Comment by cyrilletuzi** [comment]
Thanks for the details. That is indeed the issue, this lib schematics requires `@schematics/angular` >= 8 to work.

That's not normal there are still official packages on v7. You should update them all.

I'll close the issue as it's not related to this lib but an issue in Angular CLI migration.

**Comment by slo-cap3** [comment]
> That's not normal there are still official packages on v7. You should update them all.

I will, and thank you. Much appreciated 👍
